"""empty message

Revision ID: 55709530372f
Revises: f8c74cf045d9
Create Date: 2018-05-20 12:58:36.366397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '55709530372f'
down_revision = 'f8c74cf045d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_conn',
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['component.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['component.id'], )
    )
    op.create_table('component_license_conn',
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('license_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], ),
    sa.ForeignKeyConstraint(['license_id'], ['license.id'], )
    )
    op.create_table('product_component_conn',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(length=128), nullable=True),
    sa.Column('modification', sa.Boolean(), nullable=True),
    sa.Column('delivery', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'component_id')
    )
    op.drop_table('components')
    op.drop_table('licenses')
    op.drop_table('products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('component_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('relation', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('modification', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('delivery', mysql.VARCHAR(length=128), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], name='products_ibfk_1'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='products_ibfk_2'),
    sa.PrimaryKeyConstraint('product_id', 'component_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('licenses',
    sa.Column('component_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('license_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], name='licenses_ibfk_1'),
    sa.ForeignKeyConstraint(['license_id'], ['license.id'], name='licenses_ibfk_2'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('components',
    sa.Column('parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('child_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['component.id'], name='components_ibfk_1'),
    sa.ForeignKeyConstraint(['parent_id'], ['component.id'], name='components_ibfk_2'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('product_component_conn')
    op.drop_table('component_license_conn')
    op.drop_table('component_conn')
    # ### end Alembic commands ###
